"""Run with blender -b --python output/scripts/build_scene.py."""
import bpy
import sys
import json
from pathlib import Path
HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import common, materials, hero, architecture, furniture, garden, cameras


def main():
    bpy.ops.wm.read_factory_settings(use_empty=True)
    scene=bpy.context.scene
    scene.unit_settings.system='METRIC'
    scene.unit_settings.length_unit='METERS'
    m=materials.build()
    for module in (architecture,hero,furniture,garden,cameras):
        print('BUILD_STAGE',module.__name__,flush=True)
        module.build(m)
    scene.render.engine='CYCLES'
    scene.cycles.device='GPU'
    scene.cycles.samples=192
    scene.cycles.use_adaptive_sampling=True
    scene.cycles.adaptive_threshold=.015
    scene.cycles.use_denoising=True
    scene.cycles.denoiser='OPENIMAGEDENOISE'
    scene.cycles.denoising_input_passes='RGB_ALBEDO_NORMAL'
    scene.cycles.max_bounces=10
    scene.cycles.diffuse_bounces=5
    scene.cycles.glossy_bounces=5
    scene.cycles.transmission_bounces=8
    scene.cycles.transparent_max_bounces=12
    scene.cycles.sample_clamp_indirect=4
    scene.cycles.use_light_tree=True
    scene.cycles.seed=251025
    scene.cycles.use_animated_seed=False
    scene.render.resolution_x=2160
    scene.render.resolution_y=2160
    scene.render.resolution_percentage=100
    scene.render.fps=24
    scene.render.fps_base=1
    scene.frame_start=1
    scene.frame_end=864
    scene.render.image_settings.file_format='PNG'
    scene.render.image_settings.color_mode='RGB'
    scene.render.image_settings.color_depth='8'
    scene.render.image_settings.compression=30
    scene.render.film_transparent=False
    scene.render.use_persistent_data=True
    scene.view_settings.view_transform='AgX'
    scene.view_settings.look='AgX - Medium High Contrast'
    scene.view_settings.exposure=0
    scene.view_settings.gamma=1
    scene.render.filepath='//frames/frame_'
    scene['project']='Golden Hour Companion — an afternoon at home'
    scene['reference_usage']='Reference photo is used only for external comparison; zero image texture nodes.'
    scene['animation']='Four real camera moves, frames 1–864, 24 fps. Final editorial dissolves are generated by assemble.py.'
    scene['length_units']='Metres; room ceiling 3.09 m; all rooms are enclosed and connected.'
    scene['assets']='Original procedural geometry and analytic PBR shaders. No external assets.'
    scene.frame_set(1)
    for area in bpy.context.screen.areas:
        if area.type=='VIEW_3D':
            area.spaces.active.region_3d.view_perspective='CAMERA'
            area.spaces.active.shading.type='MATERIAL'
    output=HERE.parent
    bpy.ops.wm.save_as_mainfile(filepath=str(output/'golden_hour_companion.blend'),compress=True)
    summary={'blender':bpy.app.version_string,'objects':len(bpy.data.objects),
             'meshes':len(bpy.data.meshes),'materials':len(bpy.data.materials),
             'vertices':sum(len(x.vertices) for x in bpy.data.meshes),
             'polygons':sum(len(x.polygons) for x in bpy.data.meshes),
             'image_textures':sum(1 for mat in bpy.data.materials if mat.use_nodes for n in mat.node_tree.nodes if n.type=='TEX_IMAGE')}
    (output/'review'/'scene_inventory.json').write_text(json.dumps(summary,indent=2))
    print('BUILD_COMPLETE',json.dumps(summary),flush=True)


if __name__ == '__main__':
    main()
